# Frame Art Manager Add-on Configuration
name: Frame Art Manager
version: "0.10.3"
slug: frame_art_manager
description: Manage Frame TV artwork library
url: https://github.com/billyfw/ha-frame-art-manager
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  frame_art_path: /config/www/frame_art
  port: 8099
  git_remote_host_alias: "github-billy"
  ssh_private_key: []
schema:
  frame_art_path: str
  port: int
  git_remote_host_alias: str?
  ssh_private_key:
    - str?
map:
  - config:rw
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
ingress: true
ingress_port: 8099
ingress_stream: false
panel_icon: mdi:image-frame
panel_title: Frame Art Manager
webui: http://[HOST]:[PORT:8099]
homeassistant_api: false
auth_api: false
hassio_api: true
hassio_role: default
